### ISSUE TITLE
Bug: Time progression slows down when returning to page.

### ISSUE THREAD

**Issue by Gaoridang** [wowba/Sliding-Puzzle#1]
## Description
다른 창으로 갔다가 다시 돌아오면 시간이 천천히 갑니다. 체감상 1.5초마다 1초 정도 가는 느낌입니다.

**Comment by wowba** [comment]
안녕하세요!

해당 문제는 제가 타이머 로직에 사용한 setInterval이 다른 탭을 보고 있을때에는 비활성화 시키는 브라우저 정책에 의한 것 같습니다!
[https://usefulangle.com/post/280/settimeout-setinterval-on-inactive-tab](https://usefulangle.com/post/280/settimeout-setinterval-on-inactive-tab)
모든 브라우저를 확인하지는 않았지만, 브라우저 별로 비활성화 된 탭에 대한 정책이 다른 듯 합니다.

우선 해당 이슈를 해결해 보려고 합니다!
QA 감사합니다!

**Comment by Gaoridang** [comment]
아하 저는 **사파리**에서 플레이 했습니다!
많이 배워갑니다!

**Comment by wowba** [comment]
@Gaoridang 

알려주신 버그를 자바스크립트 API인 web worker 를 이용하여 수정하였습니다!

혹시 해결 방법이 궁금하시다면 worker.js 및 Timer.js의 start(), stop() 을 확인하시면 됩니다!
